# Generated by Django 4.1.6 on 2023-05-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
